### ISSUE TITLE
Cielo Plugin is Outdated

### ISSUE THREAD

**Issue by satheshk385** [claudiosanches/woocommerce-checkout-cielo#6]
Update Your plugin, According to woocommerce and wordpress latest version.

**Comment by claudiosanches** [comment]
Please feel free to submit a Pull Request.

**Comment by romeumellobr** [comment]
Oi Claudio Sanches, tudo bem? Estou pensando em atualizar esse plugin para versão 3.0 da Cielo, também ativar o modo sandbox, como vc fez no plugin do PagSeguro, e precisa acrescentar o Merchant  Key. Você pode me dar uma dicas de como eu posso mudar para essa nova API? eu posso me tornar um colaborador oficial do projeto?

**Comment by claudiosanches** [comment]
Fechando em favor de https://github.com/claudiosanches/woocommerce-checkout-cielo/issues/8

@romeumellobr vamos conversar no outro tópico.
